package org.umamo.format.cmo3

/*
 * The main.xml prologue tables a fresh document must author (docs/format/CMO3.md §3 Document
 * Shape): every element tag's fully-qualified editor class name for the <?import?> block, and the
 * 5.4-era per-class schema versions for the <?version?> block.  Both are transcribed verbatim from
 * the golden corpus (the union of all 32 samples' import PIs - zero tag collisions - and the
 * fileFormatVersion=504000000 samples' version PIs); Cmo3AuthorTest re-derives every corpus file's
 * prologue through these tables and compares verbatim, so any drift fails loudly.
 */

// CMO3: <?import FQCN?> - one per distinct non-primitive element tag, sorted by FQCN; nested
// classes use the 'dollar' spelling and the element tag is the segment after the last 'dollar' or '.'.
internal val CMO3_TAG_TO_FQCN: Map<String, String> =
	mapOf(
		"ACAffecterForm" to "com.live2d.cubism.doc.model.affecter.ACAffecterForm",
		"ACAffecterSource" to "com.live2d.cubism.doc.model.affecter.ACAffecterSource",
		"ACBlend" to "com.live2d.graphics.psd.blend.ACBlend",
		"ACDeformerForm" to "com.live2d.cubism.doc.model.deformer.ACDeformerForm",
		"ACDeformerOriginalShape" to "com.live2d.cubism.doc.model.extension.deformerOriginalShape.ACDeformerOriginalShape",
		"ACDeformerSource" to "com.live2d.cubism.doc.model.deformer.ACDeformerSource",
		"ACDrawableForm" to "com.live2d.cubism.doc.model.drawable.ACDrawableForm",
		"ACDrawableSource" to "com.live2d.cubism.doc.model.drawable.ACDrawableSource",
		"ACExtension" to "com.live2d.cubism.doc.model.extension.ACExtension",
		"ACForm" to "com.live2d.cubism.doc.model.ACForm",
		"ACImageLayer" to "com.live2d.cubism.doc.resources.ACImageLayer",
		"ACLayerEntry" to "com.live2d.cubism.doc.resources.ACLayerEntry",
		"ACLayerGroup" to "com.live2d.cubism.doc.resources.ACLayerGroup",
		"ACParameterControllableSource" to "com.live2d.cubism.doc.model.ACParameterControllableSource",
		"ACTextureInput" to "com.live2d.cubism.doc.model.extension.textureInput.ACTextureInput",
		"AClip" to "com.live2d.graphics.filter.concreteFilter.clip.AClip",
		"AFilterDef" to "com.live2d.graphics.filter.AFilterDef",
		"AMappingDetail" to "com.live2d.cubism.doc.model.motionSync.data.AMappingDetail",
		"AValueConnector" to "com.live2d.graphics.filter.AValueConnector",
		"AlphaComposition" to "com.live2d.cubism.doc.model.drawable.AlphaComposition",
		"Anisotropy" to "com.live2d.graphics3d.texture.Anisotropy",
		"AutoLayoutLock" to "com.live2d.cubism.doc.model.texture.textureAtlas.AutoLayoutLock",
		"AutoYureConfig" to "com.live2d.cubism.doc.model.deformer.autoYure.AutoYureConfig",
		"BindMethod" to "com.live2d.cubism.doc.model.extension.controller.CControllerExtension\$BindMethod",
		"CAffecterGuid" to "com.live2d.type.CAffecterGuid",
		"CAffecterId" to "com.live2d.cubism.doc.model.id.CAffecterId",
		"CAffecterSourceSet" to "com.live2d.cubism.doc.model.affecter.CAffecterSourceSet",
		"CAffine" to "com.live2d.type.CAffine",
		"CArtMeshForm" to "com.live2d.cubism.doc.model.drawable.artMesh.CArtMeshForm",
		"CArtMeshSource" to "com.live2d.cubism.doc.model.drawable.artMesh.CArtMeshSource",
		"CArtPathBrush" to "com.live2d.cubism.doc.model.drawable.artPath.Line.CArtPathBrush",
		"CArtPathBrushGuid" to "com.live2d.type.CArtPathBrushGuid",
		"CArtPathBrushId" to "com.live2d.cubism.doc.model.id.CArtPathBrushId",
		"CArtPathBrushSetting" to "com.live2d.cubism.doc.model.drawable.artPath.Line.CArtPathBrushSetting",
		"CArtPathBrush_TextureInput" to "com.live2d.cubism.doc.model.drawable.artPath.Line.CArtPathBrush_TextureInput",
		"CArtPathDrawingCurveType" to "com.live2d.cubism.doc.model.drawable.artPath.CArtPathDrawingCurveType",
		"CAutoYureConfigExtension" to "com.live2d.cubism.doc.model.extension.autoYure.CAutoYureConfigExtension",
		"CBlend_Color" to "com.live2d.graphics.psd.blend.CBlend_Color",
		"CBlend_LinearDodge" to "com.live2d.graphics.psd.blend.CBlend_LinearDodge",
		"CBlend_Multiply" to "com.live2d.graphics.psd.blend.CBlend_Multiply",
		"CBlend_Normal" to "com.live2d.graphics.psd.blend.CBlend_Normal",
		"CBlend_Normal_Original" to "com.live2d.graphics.psd.blend.CBlend_Normal_Original",
		"CBlend_NotSupported" to "com.live2d.graphics.psd.blend.CBlend_NotSupported",
		"CCachedImage" to "com.live2d.graphics.cachedImage.CCachedImage",
		"CCachedImageManager" to "com.live2d.graphics.cachedImage.CCachedImageManager",
		"CColor" to "com.live2d.type.CColor",
		"CControllerCurve" to "com.live2d.cubism.doc.model.extension.controller.CControllerCurve",
		"CControllerCurveGuid" to "com.live2d.type.CControllerCurveGuid",
		"CControllerExtension" to "com.live2d.cubism.doc.model.extension.controller.CControllerExtension",
		"CControllerPoint" to "com.live2d.cubism.doc.model.extension.controller.CControllerPoint",
		"CControllerPointGuid" to "com.live2d.type.CControllerPointGuid",
		"CCurveForRotationDeformerExtension" to "com.live2d.cubism.doc.model.affecter.glue.deformPathSkinning.CCurveForRotationDeformerExtension",
		"CDeformerGuid" to "com.live2d.type.CDeformerGuid",
		"CDeformerId" to "com.live2d.cubism.doc.model.id.CDeformerId",
		"CDeformerOriginalShapeExtension" to "com.live2d.cubism.doc.model.extension.deformerOriginalShape.CDeformerOriginalShapeExtension",
		"CDeformerSourceSet" to "com.live2d.cubism.doc.model.deformer.CDeformerSourceSet",
		"CDrawableGuid" to "com.live2d.type.CDrawableGuid",
		"CDrawableId" to "com.live2d.cubism.doc.model.id.CDrawableId",
		"CDrawableSourceSet" to "com.live2d.cubism.doc.model.drawable.CDrawableSourceSet",
		"CEditableMeshExtension" to "com.live2d.cubism.doc.model.extension.editableMesh.CEditableMeshExtension",
		"CEffectParameterGroups" to "com.live2d.cubism.doc.model.CEffectParameterGroups",
		"CExtendedInterpolationExtension" to "com.live2d.cubism.doc.model.interpolator.extendedInterpolation.CExtendedInterpolationExtension",
		"CExtensionGuid" to "com.live2d.type.CExtensionGuid",
		"CFloatColor" to "com.live2d.type.CFloatColor",
		"CFormGuid" to "com.live2d.type.CFormGuid",
		"CGameMotionSet" to "com.live2d.cubism.doc.gameData.motions.CGameMotionSet",
		"CGlueForm" to "com.live2d.cubism.doc.model.affecter.glue.CGlueForm",
		"CGlueSource" to "com.live2d.cubism.doc.model.affecter.glue.CGlueSource",
		"CGuideGuid" to "com.live2d.type.CGuideGuid",
		"CGuide_Modeling" to "com.live2d.cubism.doc.modeling.ui.guide.CGuide_Modeling",
		"CGuidesSetting" to "com.live2d.cubism.doc.modeling.ui.guide.CGuidesSetting",
		"CImageCanvas" to "com.live2d.graphics.CImageCanvas",
		"CImageIcon" to "com.live2d.type.CImageIcon",
		"CImageResource" to "com.live2d.graphics.CImageResource",
		"CLabelColor" to "com.live2d.cubism.doc.model.CLabelColor",
		"CLabelColorType" to "com.live2d.cubism.doc.model.CLabelColorType",
		"CLayer" to "com.live2d.cubism.doc.resources.CLayer",
		"CLayerGroup" to "com.live2d.cubism.doc.resources.CLayerGroup",
		"CLayerGuid" to "com.live2d.type.CLayerGuid",
		"CLayerIdentifier" to "com.live2d.cubism.doc.resources.CLayerIdentifier",
		"CLayerInputData" to "com.live2d.cubism.doc.model.extension.textureInput.inputFilter.CLayerInputData",
		"CLayerSelectorMap" to "com.live2d.cubism.doc.model.extension.textureInput.inputFilter.CLayerSelectorMap",
		"CLayeredImage" to "com.live2d.cubism.doc.resources.CLayeredImage",
		"CLayeredImageGuid" to "com.live2d.type.CLayeredImageGuid",
		"CMeshGeneratorExtension" to "com.live2d.cubism.doc.model.extension.meshGenerator.CMeshGeneratorExtension",
		"CMocExportType" to "com.live2d.cubism.doc.model.exporter.CMocExportType",
		"CModelExportSettingDialogData" to "com.live2d.cubism.doc.model.exporter.CModelExportSettingDialogData",
		"CModelGuid" to "com.live2d.type.CModelGuid",
		"CModelImage" to "com.live2d.cubism.doc.model.texture.modelImage.CModelImage",
		"CModelImageGroup" to "com.live2d.cubism.doc.model.texture.modelImage.CModelImageGroup",
		"CModelImageGuid" to "com.live2d.type.CModelImageGuid",
		"CModelInfo" to "com.live2d.cubism.doc.model.CModelInfo",
		"CModelSource" to "com.live2d.cubism.doc.model.CModelSource",
		"CModelStateSetSet" to "com.live2d.cubism.doc.model.modelStateSet.CModelStateSetSet",
		"CMotionSyncSettingGuid" to "com.live2d.type.CMotionSyncSettingGuid",
		"CMotionSyncSettingId" to "com.live2d.cubism.doc.model.id.CMotionSyncSettingId",
		"CMotionSyncSettingSource" to "com.live2d.cubism.doc.model.motionSync.CMotionSyncSettingSource",
		"CMotionSyncSettingSourceSet" to "com.live2d.cubism.doc.model.motionSync.CMotionSyncSettingSourceSet",
		"CParameterGroup" to "com.live2d.cubism.doc.model.param.group.CParameterGroup",
		"CParameterGroupGuid" to "com.live2d.type.CParameterGroupGuid",
		"CParameterGroupId" to "com.live2d.cubism.doc.model.id.CParameterGroupId",
		"CParameterGroupSet" to "com.live2d.cubism.doc.model.param.group.CParameterGroupSet",
		"CParameterGuid" to "com.live2d.type.CParameterGuid",
		"CParameterId" to "com.live2d.cubism.doc.model.id.CParameterId",
		"CParameterSource" to "com.live2d.cubism.doc.model.param.CParameterSource",
		"CParameterSourceSet" to "com.live2d.cubism.doc.model.param.CParameterSourceSet",
		"CPartForm" to "com.live2d.cubism.doc.model.parts.CPartForm",
		"CPartGuid" to "com.live2d.type.CPartGuid",
		"CPartId" to "com.live2d.cubism.doc.model.id.CPartId",
		"CPartSource" to "com.live2d.cubism.doc.model.parts.CPartSource",
		"CPartSourceSet" to "com.live2d.cubism.doc.model.parts.CPartSourceSet",
		"CPhysicsDataGuid" to "com.live2d.type.CPhysicsDataGuid",
		"CPhysicsInput" to "com.live2d.cubism.doc.gameData.physics.CPhysicsInput",
		"CPhysicsOutput" to "com.live2d.cubism.doc.gameData.physics.CPhysicsOutput",
		"CPhysicsSettingId" to "com.live2d.cubism.doc.model.id.CPhysicsSettingId",
		"CPhysicsSettingsGuid" to "com.live2d.type.CPhysicsSettingsGuid",
		"CPhysicsSettingsSource" to "com.live2d.cubism.doc.gameData.physics.CPhysicsSettingsSource",
		"CPhysicsSettingsSourceSet" to "com.live2d.cubism.doc.gameData.physics.CPhysicsSettingsSourceSet",
		"CPhysicsSourceType" to "com.live2d.cubism.doc.gameData.physics.CPhysicsController\$CPhysicsSourceType",
		"CPhysicsVertex" to "com.live2d.cubism.doc.gameData.physics.CPhysicsVertex",
		"CPoint" to "com.live2d.type.CPoint",
		"CRandomPoseGroupData" to "com.live2d.cubism.doc.model.randomPose.CRandomPoseSetting\$CRandomPoseGroupData",
		"CRandomPoseParamData" to "com.live2d.cubism.doc.model.randomPose.CRandomPoseSetting\$CRandomPoseParamData",
		"CRandomPoseSetting" to "com.live2d.cubism.doc.model.randomPose.CRandomPoseSetting",
		"CRandomPoseSettingManager" to "com.live2d.cubism.doc.model.randomPose.CRandomPoseSettingManager",
		"CRect" to "com.live2d.type.CRect",
		"CRotationDeformerForm" to "com.live2d.cubism.doc.model.deformer.rotation.CRotationDeformerForm",
		"CRotationDeformerSource" to "com.live2d.cubism.doc.model.deformer.rotation.CRotationDeformerSource",
		"CSize" to "com.live2d.type.CSize",
		"CTextureAtlas" to "com.live2d.cubism.doc.model.texture.textureAtlas.CTextureAtlas",
		"CTextureAtlasGuid" to "com.live2d.type.CTextureAtlasGuid",
		"CTextureImage" to "com.live2d.cubism.doc.model.texture.CTextureImage",
		"CTextureInputExtension" to "com.live2d.cubism.doc.model.extension.textureInput.CTextureInputExtension",
		"CTextureInput_ModelImage" to "com.live2d.cubism.doc.model.extension.textureInput.CTextureInput_ModelImage",
		"CTextureInput_TextureAtlasRegion" to "com.live2d.cubism.doc.model.extension.textureInput.CTextureInput_TextureAtlasRegion",
		"CTextureManager" to "com.live2d.cubism.doc.model.texture.CTextureManager",
		"CTopologyObserverExtension" to "com.live2d.cubism.doc.model.extension.structureObserver.CTopologyObserverExtension",
		"CWarpDeformerBezierExtension" to "com.live2d.cubism.doc.model.extension.warpBezier.CWarpDeformerBezierExtension",
		"CWarpDeformerForm" to "com.live2d.cubism.doc.model.deformer.warp.CWarpDeformerForm",
		"CWarpDeformerSource" to "com.live2d.cubism.doc.model.deformer.warp.CWarpDeformerSource",
		"CWritableImage" to "com.live2d.graphics.CWritableImage",
		"CachedImageType" to "com.live2d.graphics.cachedImage.CachedImageType",
		"ClipByMesh" to "com.live2d.graphics.filter.concreteFilter.clip.ClipByMesh",
		"ColorComposition" to "com.live2d.cubism.doc.model.drawable.ColorComposition",
		"CompatibilityOption_Cubism21to30" to "com.live2d.cubism.doc.model.options.compatibility.CompatibilityOption_Cubism21to30",
		"ConstValueConnector" to "com.live2d.graphics.filter.concreteConnector.ConstValueConnector",
		"CoordType" to "com.live2d.doc.CoordType",
		"CreationMethod" to "com.live2d.cubism.doc.model.extension.deformerOriginalShape.ACDeformerOriginalShape\$CreationMethod",
		"CurveElement" to "com.live2d.cubism.doc.model.affecter.glue.deformPathSkinning.CCurveForRotationDeformerExtension\$CurveElement",
		"EditorEdition" to "com.live2d.cubism.doc.model.options.edition.EditorEdition",
		"Effect" to "com.live2d.cubism.doc.model.extension.controller.CControllerExtension\$Effect",
		"EffectParameterType" to "com.live2d.cubism.doc.model.EffectParameterType",
		"EmptyFilter" to "com.live2d.graphics.filter.concreteFilter.EmptyFilter",
		"EnvConnection" to "com.live2d.graphics.filter.FilterSet\$EnvConnection",
		"EnvValueConnector" to "com.live2d.graphics.filter.concreteConnector.EnvValueConnector",
		"EnvValueSet" to "com.live2d.graphics.filter.FilterEnv\$EnvValueSet",
		"ExtendedInterpolationSetting" to "com.live2d.cubism.doc.model.morphTarget.extendedInterpolation.ExtendedInterpolationSetting",
		"ExtendedInterpolationType" to "com.live2d.cubism.doc.model.interpolator.extendedInterpolation.ExtendedInterpolationType",
		"ExtendedKeyFormMorphTarget" to "com.live2d.cubism.doc.model.morphTarget.extendedInterpolation.ExtendedKeyFormMorphTarget",
		"ExtendedKeyFormMorphTargetSet" to "com.live2d.cubism.doc.model.morphTarget.extendedInterpolation.ExtendedKeyFormMorphTargetSet",
		"FilterDefGuid" to "com.live2d.type.FilterDefGuid",
		"FilterEnv" to "com.live2d.graphics.filter.FilterEnv",
		"FilterInstance" to "com.live2d.graphics.filter.filterInstance.FilterInstance",
		"FilterInstanceId" to "com.live2d.graphics.filter.id.FilterInstanceId",
		"FilterMode" to "com.live2d.graphics3d.texture.GTexture\$FilterMode",
		"FilterOutputValueConnector" to "com.live2d.graphics.filter.concreteConnector.FilterOutputValueConnector",
		"FilterSet" to "com.live2d.graphics.filter.FilterSet",
		"FilterValue" to "com.live2d.graphics.filter.FilterValue",
		"FilterValueId" to "com.live2d.graphics.filter.id.FilterValueId",
		"FixWidthData" to "com.live2d.cubism.doc.model.drawable.artPath.Line.FixWidthData",
		"FormatVersion" to "com.live2d.cubism.doc.model.exporter.CModelExportSettingDialogData\$FormatVersion",
		"GEditableMesh2" to "com.live2d.graphics3d.editableMesh.GEditableMesh2",
		"GEditableMeshGuid" to "com.live2d.type.GEditableMeshGuid",
		"GTexture" to "com.live2d.graphics3d.texture.GTexture",
		"GTexture2D" to "com.live2d.graphics3d.texture.GTexture2D",
		"GTextureGuid" to "com.live2d.type.GTextureGuid",
		"GTransform2" to "com.live2d.graphics3d.component.GTransform2",
		"GVector2" to "com.live2d.graphics3d.type.GVector2",
		"GuideType" to "com.live2d.cubism.doc.modeling.ui.guide.CGuide_Modeling\$GuideType",
		"IdSet" to "com.live2d.cubism.doc.model.options.compatibility.CompatibilityOption_Cubism21to30\$IdSet",
		"InterpolationType" to "com.live2d.cubism.doc.model.interpolator.InterpolationType",
		"KeyFormMorphTarget" to "com.live2d.cubism.doc.model.morphTarget.KeyFormMorphTarget",
		"KeyFormMorphTargetSet" to "com.live2d.cubism.doc.model.morphTarget.KeyFormMorphTargetSet",
		"KeyOnParameter" to "com.live2d.cubism.doc.model.interpolator.KeyOnParameter",
		"KeyformBindingSource" to "com.live2d.cubism.doc.model.interpolator.KeyformBindingSource",
		"KeyformGridAccessKey" to "com.live2d.cubism.doc.model.interpolator.KeyformGridAccessKey",
		"KeyformGridSource" to "com.live2d.cubism.doc.model.interpolator.KeyformGridSource",
		"KeyformOnGrid" to "com.live2d.cubism.doc.model.interpolator.KeyformOnGrid",
		"LayerSet" to "com.live2d.cubism.doc.resources.LayerSet",
		"LayeredImageWrapper" to "com.live2d.cubism.doc.model.texture.LayeredImageWrapper",
		"MagFilter" to "com.live2d.graphics3d.texture.MagFilter",
		"MappingItem" to "com.live2d.cubism.doc.model.motionSync.data.MappingItem",
		"MeshGenerateSetting" to "com.live2d.cubism.doc.model.extension.meshGenerator.MeshGenerateSetting",
		"MeshPointRef" to "com.live2d.cubism.doc.model.drawable.artMesh.MeshPointRef",
		"MeshPointRefEx" to "com.live2d.cubism.doc.model.drawable.artMesh.MeshPointRefEx",
		"MinFilter" to "com.live2d.graphics3d.texture.MinFilter",
		"ModelImageEntry" to "com.live2d.cubism.doc.model.texture.textureAtlas.CTextureAtlas\$ModelImageEntry",
		"ModelImageFilterEnv" to "com.live2d.cubism.doc.model.extension.textureInput.inputFilter.ModelImageFilterEnv",
		"ModelImageFilterSet" to "com.live2d.cubism.doc.model.extension.textureInput.inputFilter.ModelImageFilterSet",
		"ModelViewerSetting" to "com.live2d.cubism.doc.modeling.ui.viewer.ModelViewerSetting",
		"MorphTargetBlendWeightConstraint" to "com.live2d.cubism.doc.model.morphTarget.MorphTargetBlendWeightConstraint",
		"MorphTargetBlendWeightConstraintSet" to "com.live2d.cubism.doc.model.morphTarget.MorphTargetBlendWeightConstraintSet",
		"MorphTargetEditBaseParameterMap" to "com.live2d.cubism.doc.model.morphTarget.MorphTargetEditBaseParameterMap",
		"MotionSyncMappingSetting" to "com.live2d.cubism.doc.model.motionSync.MotionSyncMappingSetting",
		"MotionSyncPostProcSetting" to "com.live2d.cubism.doc.model.motionSync.MotionSyncPostProcSetting",
		"PointInTriangle" to "com.live2d.cubism.doc.model.drawable.artMesh.PointInTriangle",
		"PointOnCurve" to "com.live2d.cubism.doc.model.extension.controller.CControllerExtension\$PointOnCurve",
		"RotationDeformerOriginalShape" to "com.live2d.cubism.doc.model.extension.deformerOriginalShape.RotationDeformerOriginalShape",
		"SettingType" to "com.live2d.cubism.doc.model.motionSync.SettingType",
		"ShapeMappingDetail" to "com.live2d.cubism.doc.model.motionSync.data.ShapeMappingDetail",
		"SpriteData" to "com.live2d.cubism.doc.model.drawable.artPath.Line.SpriteData",
		"StaticFilterDefGuid" to "com.live2d.type.StaticFilterDefGuid",
		"SyncAudioParam" to "com.live2d.cubism.doc.model.motionSync.data.SyncAudioParam",
		"SyncAudioParamGuid" to "com.live2d.type.SyncAudioParamGuid",
		"SyncCubismParam" to "com.live2d.cubism.doc.model.motionSync.data.SyncCubismParam",
		"SyncCubismParamGuid" to "com.live2d.type.SyncCubismParamGuid",
		"SyncType" to "com.live2d.cubism.doc.model.motionSync.SyncType",
		"TargetPoint" to "com.live2d.cubism.doc.model.extension.controller.CControllerExtension\$TargetPoint",
		"TextureImageGroup" to "com.live2d.cubism.doc.model.texture.TextureImageGroup",
		"TextureState" to "com.live2d.cubism.doc.model.drawable.TextureState",
		"TextureUvData" to "com.live2d.cubism.doc.model.drawable.artPath.Line.TextureUvData",
		"TrackCursorSetting" to "com.live2d.cubism.doc.modeling.ui.viewer.TrackCursorSetting",
		"TrackCursorSettingItemType" to "com.live2d.cubism.doc.modeling.ui.viewer.TrackCursorSettingItemType",
		"Type" to "com.live2d.cubism.doc.model.param.CParameterSource\$Type",
		"WarpDeformerOriginalShape" to "com.live2d.cubism.doc.model.extension.deformerOriginalShape.WarpDeformerOriginalShape",
		"WrapMode" to "com.live2d.graphics3d.texture.WrapMode",
		"YureDeformConfig" to "com.live2d.cubism.doc.model.deformer.autoYure.YureDeformConfig",
		"YureRootDirection" to "com.live2d.cubism.doc.model.deformer.autoYure.YureRootDirection",
	)

// CMO3: <?version Name:N?> - emitted regardless of document content in every corpus file
// (SerializeFormatVersion is never an element tag).
internal val CMO3_VERSIONS_ALWAYS_5_4: List<Pair<String, Int>> =
	listOf(
		"SerializeFormatVersion" to 2,
	)

// CMO3: <?version Name:N?> - emitted when the keyed element tag is present in the document.  The
// PI name is the tag itself except for ModelImageEntry, whose version PI spells the dotted
// outer-class-less FQN while its import PI spells CTextureAtlas.ModelImageEntry with a dollar,
// and ModelStateSet, whose versioned item class rides on its (possibly empty) set's tag.
// The versions are the highest observed across the corpus (each class's current version at the
// eras our corpus spans); a versioned class MISSING from this table is load-bearing to get right:
// the editor's reader falls back to deserializing that class at version 0, and a v0 layout read
// over our current-version element NPEs field-by-field (CRotationDeformerForm was the proof - its
// PI rides only on corpus files that contain rotation deformers, so a table built from blank
// saves alone never sees it).
internal val CMO3_VERSIONS_BY_TAG_5_4: Map<String, Pair<String, Int>> =
	mapOf(
		"CModelStateSetSet" to ("ModelStateSet" to 1),
		"ACDeformerOriginalShape" to ("ACDeformerOriginalShape" to 1),
		"CArtMeshSource" to ("CArtMeshSource" to 5),
		"CArtPathBrush" to ("CArtPathBrush" to 1),
		"CArtPathBrush_TextureInput" to ("CArtPathBrush_TextureInput" to 1),
		"CFloatColor" to ("CFloatColor" to 1),
		"CGuide_Modeling" to ("CGuide_Modeling" to 1),
		"CLabelColor" to ("CLabelColor" to 0),
		"CModelImage" to ("CModelImage" to 3),
		"CModelSource" to ("CModelSource" to 16),
		"CParameterGroup" to ("CParameterGroup" to 4),
		"CPartForm" to ("CPartForm" to 2),
		"CPartSource" to ("CPartSource" to 2),
		"CRotationDeformerForm" to ("CRotationDeformerForm" to 1),
		"FixWidthData" to ("FixWidthData" to 1),
		"KeyFormMorphTarget" to ("KeyFormMorphTarget" to 2),
		"KeyformGridSource" to ("KeyformGridSource" to 1),
		"ModelImageEntry" to ("com.live2d.cubism.doc.model.texture.textureAtlas.ModelImageEntry" to 2),
		"RotationDeformerOriginalShape" to ("RotationDeformerOriginalShape" to 1),
		"SpriteData" to ("SpriteData" to 1),
		"TextureUvData" to ("TextureUvData" to 1),
		"WarpDeformerOriginalShape" to ("WarpDeformerOriginalShape" to 1),
	)

// Tags owned by the serializer itself (structural, primitive, collection, and array tags) - they
// deserialize without a class and therefore carry no import PI.
internal val CMO3_STRUCTURAL_TAGS: Set<String> =
	setOf(
		"root",
		"main",
		"shared",
		"entry",
		"null",
		"file",
		"i",
		"f",
		"d",
		"l",
		"short",
		"byte",
		"char",
		"b",
		"s",
		"array_list",
		"carray_list",
		"hash_map",
		"linked_map",
		"linked_set",
		"float-array",
		"int-array",
		"long-array",
		"short-array",
		"double-array",
		"byte-array",
		"char-array",
		"bool-array",
	)
